### ISSUE TITLE
job_type branch and deps on File[/usr/bin/gem] File[/usr/bin/ruby]

### ISSUE THREAD

**Issue by fessyfoo** [voxpupuli/puppet-rundeck#119]
@liamjbennett  per our convo,  here's the issue using the [job_type](https://github.com/puppet-community/puppet-rundeck/tree/job_type) branch

 [job_type](https://github.com/puppet-community/puppet-rundeck/tree/job_type) branch introduces  a dep on File[/usr/bin/gem] File[/usr/bin/ruby]  which in our installations are managed by virtue of managing the deb packages that provide them and as such are not in the catalog.  

https://github.com/puppet-community/puppet-rundeck/blob/job_type/manifests/install.pp#L46

I'm not sure the correct solution,  but it seems that a more widely used open source module perhaps shouldn't have such strict dependencies. 

[ note @carlf  ]

**Comment by jyaworski** [comment]
Could you explain a bit more about this?

**Comment by fessyfoo** [comment]
int he job_type branch, linked above  there's this: 

```
ensure_resource('package', ['libxml2'], {'ensure' => 'installed', 'require' => ['File[/usr/bin/ruby]','File[/usr/bin/gem]']})
```

a dep on  specific file resources. for `/usr/bin/ruby` and `/usr/bin/gem`  if you got your ruby from say a package resource, then this file resource doesn't exist in the catalog,  and this dep fails.   at least I think that's how we stumbled into the issue.

**Comment by jyaworski** [comment]
@fessyfoo OK, that makes sense. There should likely be a better test for that. I'll take a look.

**Comment by jyaworski** [comment]
Actually, this looks like it's related to #33, which is arguably no longer needed due to the SCM plugin. Is there a need to specify jobs in Puppet, when Rundeck integrates with git natively now? When I updated to 2.6.1 I no longer cared about specifying Rundeck jobs in Puppet.

**Comment by liamjbennett** [comment]
How many instances/environments do you have rundeck in? Do they all run off a single repo? 

We have multiple environments that share some but not all projects and jobs.

Do you have projects that have the same job(s)? How do you deal with that?

**Comment by jyaworski** [comment]
@liamjbennett We have each of our projects export to their own YAML file in a repo. We don't do shared jobs cross-project due to some quirks in our environment; each project/team/etc is completely responsible for their job content, and we only provide the infrastructure to run it on. We have it in three environments currently (growing to be eight in the next six months). Each environment commits/pulls to/from its own branch, and we use PRs as a form of QA going from dev->prod.

**Comment by liamjbennett** [comment]
That actually sounds great and I guess solves the issue of keeping the jobs in sync. 

We are using this branch to puppet manage our jobs because we have jobs that are duplicated (or very similar) between projects and also some projects and jobs that only occur in one environment. I still think there might be some use cases for puppet-management but i'm open to alternatives.

Having said all that we are also looking at some alternatives around using the api to auto-generate some of our jobs so perhaps our use of this will also decline.

I just want to make sure we are considering all the use cases for job management.

**Comment by fessyfoo** [comment]
I'm just closing this because it's old.
