### ISSUE TITLE
Evaluation Error: Unknown variable: 'facts'

### ISSUE THREAD

**Issue by abondi** [voxpupuli/puppet-rundeck#328]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 2.0.0p648
- Distribution: CentOS 7
- Module version: 4.0.1

## What are you seeing
Puppet unable to complete it's run

## What behaviour did you expect instead
Either for the module to skip the facts or populate them correctly to allow completion. 

## Output log

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Unknown variable: 'facts'. at /etc/puppet/environments/production/modules/rundeck/manifests/params.pp:37:17 on node xxNodexx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by bastelfreak** [comment]
Hi @abondi, this module doesn't support puppet3 anymore. puppet3 is end of life since a long time, puppet4 is available for a few years and puppet5 got released a few days back. You should really really from this insecure version (same applies to your ruby version). You can contact us 24/7 in the irc channel #voxpupuli on freenode. We're happy to help you with the migration.
