### ISSUE TITLE
Rundeck 3.1 does not require rundeck-config package anymore

### ISSUE THREAD

**Issue by danifr** [voxpupuli/puppet-rundeck#419]
[Official info:](https://docs.rundeck.com/3.1.0-rc2/upgrading/upgrade-to-rundeck-3.1.html)

> There is now only a single RPM package required (no rundeck-config anymore)

Line to change if version >= 3.1--> https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/install.pp#L72

**Comment by danifr** [comment]
Fx for this issue here: https://github.com/voxpupuli/puppet-rundeck/pull/418
Not sure if is backwards compatible with <v3.1....

**Comment by smasa90** [comment]
I've done a duplicate because I havn't seen this PR before
https://github.com/voxpupuli/puppet-rundeck/pull/420
Adding some information :
- I've opened an issue here
https://github.com/rundeck/rundeck/issues/5168
Travis checks fail because `rundeck` package is still dependant of `rundeck-config` package on `CentOS 7`

**Comment by danifr** [comment]
Merged https://github.com/voxpupuli/puppet-rundeck/pull/422
