### ISSUE TITLE
manage SCM configuration of projects

### ISSUE THREAD

**Issue by wladikz** [voxpupuli/puppet-rundeck#541]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
   7.0
- Ruby:
- Distribution:
   Ubuntu
- Module version:
  9.1.0

## How to reproduce (e.g Puppet code you use)
in module versions up to 8.0.1 there is functionality to manage project SCM configuration
how to configure SCM in version 9.1.0

**Comment by Joris29** [comment]
Hello @wladikz, there is a small doc that should get you on your way all the options can be added as project config see docs: https://github.com/voxpupuli/puppet-rundeck/tree/master?tab=readme-ov-file#configure-rundeck-class-with-projects

**Comment by Joris29** [comment]
If it's not clear don't hesitate to ask further questions

**Comment by Joris29** [comment]
After a briefer look on the SCM part I came to the conclusion that with the current module version 9.1.0 there is no support yet.

From rundeck docs: Configuration files for the project (previously stored on-disk) are stored in the database. (Since Rundeck 3.4).

This means if you are under Rundeck 3.4 you can still use the old module version if you are above it then you have to write the proper puppet code to make the cli call because those are not added yet.

If u need help or anything you can always contact me.
